services:
  # Postgres 설정
  # - https://hub.docker.com/_/postgres
  db:
    image: postgres:14.5-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 30700:5432
    environment:
      POSTGRES_DB: inabase
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

volumes:
  db-data:
